In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({"foo": [1, 2, 3], "bar": [4, 5, 6]})

subset = df["foo"]

subset.iloc[0] = 100

df

foo  bar
0  100    4
1    2    5
2    3    6

In [3]:
pd.options.mode.copy_on_write = True

df = pd.DataFrame({"foo": [1, 2, 3], "bar": [4, 5, 6]})

subset = df["foo"]

subset.iloc[0] = 100

df

foo  bar
0    1    4
1    2    5
2    3    6

In [4]:
pd.options.mode.copy_on_write = False

In [6]:
pd.options.mode.copy_on_write = "warn"

In [7]:
ser = pd.Series([1, 2, 3])

ser.to_numpy()

array([1, 2, 3], dtype=int64)

In [8]:
df = pd.DataFrame({"foo": [1, 2, 3], "bar": [4, 5, 6]})

subset = df["foo"]

subset.iloc[0] = 100

df

C:\Users\YOSSI\AppData\Local\Temp\ipykernel_39680\83219138.py:5: FutureWarning: Setting a value on a view: behaviour will change in pandas 3.0.
You are mutating a Series or DataFrame object, and currently this mutation will
also have effect on other Series or DataFrame objects that share data with this
object. In pandas 3.0 (with Copy-on-Write), updating one Series or DataFrame object
will never modify another.

  subset.iloc[0] = 100


foo  bar
0  100    4
1    2    5
2    3    6

In [9]:
df = pd.DataFrame({"foo": [1, 2, 3], "bar": [4, 5, 6]})

df["foo"].replace(1, 5, inplace=True)

df

C:\Users\YOSSI\AppData\Local\Temp\ipykernel_39680\1394153153.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["foo"].replace(1, 5, inplace=True)
C:\Users\YOSSI\AppData\Local\Temp\ipykernel_39680\1394153153.py:3: FutureWarning: Setting a value on a view: behaviour will change in pandas 3.0.
You are mutating a Series or DataFrame object, and currently this mutation will
also have effect on other Series or DataFrame objects that share data with this
object. In pandas 3.0 (with Copy-on-Write), updating one Series or DataFram

foo  bar
0    5    4
1    2    5
2    3    6

In [10]:
df = pd.DataFrame({"foo": [1, 2, 3], "bar": [4, 5, 6]})

df.replace({"foo": {1: 5}}, inplace=True)

df

foo  bar
0    5    4
1    2    5
2    3    6

In [14]:
df = pd.DataFrame({"foo": [1, 2, 3], "bar": [4, 5, 6]})

df["foo"] = df["foo"].replace(1, 5)

df

foo  bar
0    5    4
1    2    5
2    3    6

In [15]:
df = pd.DataFrame({"foo": [1, 2, 3], "bar": [4, 5, 6]})

df.iloc[0, 0] = 100

df

foo  bar
0  100    4
1    2    5
2    3    6

In [16]:
df = pd.DataFrame({"foo": [1, 2, 3], "bar": [4, 5, 6]})

df

foo  bar
0    1    4
1    2    5
2    3    6

In [17]:
df2 = df.reset_index(drop=True)
df2

foo  bar
0    1    4
1    2    5
2    3    6

In [18]:
df2.iloc[0, 0] = 100

df

foo  bar
0    1    4
1    2    5
2    3    6

In [19]:
df2

foo  bar
0  100    4
1    2    5
2    3    6

In [20]:
df = pd.DataFrame({"foo": [1, 2, 3], "bar": [4, 5, 6]})

df = df.reset_index(drop=True)

df.iloc[0, 0] = 100

df

foo  bar
0  100    4
1    2    5
2    3    6

In [21]:
with pd.option_context("mode.copy_on_write", False):

    df = pd.DataFrame({"foo": [1, 2, 3], "bar": [4, 5, 6]})

    view = df[:]

    df.iloc[0, 0] = 100



df

foo  bar
0  100    4
1    2    5
2    3    6

In [22]:
view

foo  bar
0  100    4
1    2    5
2    3    6

In [31]:
pd.options.mode.copy_on_write = "warn"

In [32]:
df = pd.DataFrame({"foo": [1, 2, 3], "bar": [4, 5, 6]})

view = df[:]

df.iloc[0, 0] = 100

df

C:\Users\YOSSI\AppData\Local\Temp\ipykernel_39680\1355080378.py:5: FutureWarning: Setting a value on a view: behaviour will change in pandas 3.0.
You are mutating a Series or DataFrame object, and currently this mutation will
also have effect on other Series or DataFrame objects that share data with this
object. In pandas 3.0 (with Copy-on-Write), updating one Series or DataFrame object
will never modify another.

  df.iloc[0, 0] = 100


foo  bar
0  100    4
1    2    5
2    3    6

In [33]:
view

foo  bar
0  100    4
1    2    5
2    3    6

In [34]:
with pd.option_context("mode.copy_on_write", False):

    df = pd.DataFrame({"foo": [1, 2, 3], "bar": [4, 5, 6]})

    df["foo"][df["bar"] > 5] = 100

    df

C:\Users\YOSSI\AppData\Local\Temp\ipykernel_39680\3803554900.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["foo"][df["bar"] > 5] = 100


In [35]:
df = pd.DataFrame({"foo": [1, 2, 3], "bar": [4, 5, 6]})

df["foo"][df["bar"] > 5] = 100

C:\Users\YOSSI\AppData\Local\Temp\ipykernel_39680\618262324.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["foo"][df["bar"] > 5] = 100


In [36]:
df.loc[df["bar"] > 5, "foo"] = 100

In [37]:
df

foo  bar
0    1    4
1    2    5
2  100    6

In [38]:
df = pd.DataFrame({"a": [1, 2], "b": [1.5, 2.5]})

df.to_numpy()

array([[1. , 1.5],
       [2. , 2.5]])

In [39]:
df = pd.DataFrame({"a": [1, 2], "b": [3, 4]})

df.to_numpy()

array([[1, 3],
       [2, 4]], dtype=int64)

In [46]:
pd.options.mode.copy_on_write = "warn"

In [45]:
# raise error with pd.options.mode.copy_on_write = True
#arr = df.to_numpy()
#arr[0, 0] = 100 #array is read only with CoW

In [47]:
arr = df.to_numpy()

arr.flags.writeable = True

arr[0, 0] = 100

arr

array([[100,   3],
       [  2,   4]], dtype=int64)

In [48]:
df = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})

df2 = df.reset_index(drop=True)

df2.iloc[0, 0] = 100

In [49]:
df2

a  b
0  100  4
1    2  5
2    3  6

In [50]:
df

a  b
0  1  4
1  2  5
2  3  6

In [51]:
df = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})

df = df.reset_index(drop=True)

df.iloc[0, 0] = 100

In [52]:
pd.set_option("mode.copy_on_write", True)

pd.options.mode.copy_on_write = True