In [1]:
import pandas as pd
import numpy as np

In [2]:
index = pd.date_range("1/1/2000", periods=8)
index

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')

In [3]:
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])
s

a    0.226653
b    0.536675
c    1.472243
d   -1.098187
e    0.333052
dtype: float64

In [4]:
df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=["A", "B", "C"])
df

A         B         C
2000-01-01  0.121080  0.678015 -0.946181
2000-01-02 -0.011672  0.097127  0.771051
2000-01-03 -1.329823 -0.866895 -1.810622
2000-01-04  1.397277  0.048422  1.327762
2000-01-05  1.993280 -1.455339  1.473374
2000-01-06  0.878855  0.532600 -1.753983
2000-01-07  2.483546 -0.568352 -0.304539
2000-01-08  0.691885  0.046702  0.886395

In [5]:
long_series = pd.Series(np.random.randn(1000))

long_series.head()

0    1.289646
1   -1.068033
2   -0.277597
3    0.345562
4    0.223636
dtype: float64

In [6]:
long_series.tail(3)

997   -0.150359
998    1.369789
999    0.257525
dtype: float64

In [7]:
df[:2]

A         B         C
2000-01-01  0.121080  0.678015 -0.946181
2000-01-02 -0.011672  0.097127  0.771051

In [8]:
df.columns = [x.lower() for x in df.columns]
df.columns

Index(['a', 'b', 'c'], dtype='object')

In [9]:
df

a         b         c
2000-01-01  0.121080  0.678015 -0.946181
2000-01-02 -0.011672  0.097127  0.771051
2000-01-03 -1.329823 -0.866895 -1.810622
2000-01-04  1.397277  0.048422  1.327762
2000-01-05  1.993280 -1.455339  1.473374
2000-01-06  0.878855  0.532600 -1.753983
2000-01-07  2.483546 -0.568352 -0.304539
2000-01-08  0.691885  0.046702  0.886395

In [10]:
s

a    0.226653
b    0.536675
c    1.472243
d   -1.098187
e    0.333052
dtype: float64

In [11]:
s.array

<NumpyExtensionArray>
[0.22665273101563216,  0.5366748785428379,  1.4722429958286873,
 -1.0981873168171383, 0.33305235062824184]
Length: 5, dtype: float64

In [12]:
s.index.array

<NumpyExtensionArray>
['a', 'b', 'c', 'd', 'e']
Length: 5, dtype: object

In [13]:
s.to_numpy()

array([ 0.22665273,  0.53667488,  1.472243  , -1.09818732,  0.33305235])

In [14]:
np.asarray(s)

array([ 0.22665273,  0.53667488,  1.472243  , -1.09818732,  0.33305235])

In [15]:
ser = pd.Series(pd.date_range("2000", periods=2, tz="CET"))
ser


0   2000-01-01 00:00:00+01:00
1   2000-01-02 00:00:00+01:00
dtype: datetime64[ns, CET]

In [16]:
ser.to_numpy(dtype=object)

array([Timestamp('2000-01-01 00:00:00+0100', tz='CET'),
       Timestamp('2000-01-02 00:00:00+0100', tz='CET')], dtype=object)

In [17]:
ser.to_numpy(dtype="datetime64[ns]")

array(['1999-12-31T23:00:00.000000000', '2000-01-01T23:00:00.000000000'],
      dtype='datetime64[ns]')

In [18]:
df.to_numpy()

array([[ 0.12108027,  0.67801528, -0.94618061],
       [-0.01167243,  0.09712694,  0.77105124],
       [-1.32982273, -0.86689492, -1.81062194],
       [ 1.39727723,  0.04842226,  1.32776197],
       [ 1.99328019, -1.4553394 ,  1.47337378],
       [ 0.87885505,  0.53260025, -1.75398331],
       [ 2.48354577, -0.56835242, -0.30453878],
       [ 0.69188511,  0.04670164,  0.88639474]])

In [19]:
pd.set_option("compute.use_bottleneck", True)
pd.set_option("compute.use_numexpr", True)

In [20]:
df = pd.DataFrame(

    {

        "one": pd.Series(np.random.randn(3), index=["a", "b", "c"]),

        "two": pd.Series(np.random.randn(4), index=["a", "b", "c", "d"]),

        "three": pd.Series(np.random.randn(3), index=["b", "c", "d"]),

    }

)



df

one       two     three
a  0.342308 -0.698858       NaN
b  1.393615  1.504289 -0.084983
c  0.098764  0.993717 -0.256028
d       NaN -0.314475 -1.694800

In [21]:
row = df.iloc[1]
row

one      1.393615
two      1.504289
three   -0.084983
Name: b, dtype: float64

In [22]:
column = df["two"]
column

a   -0.698858
b    1.504289
c    0.993717
d   -0.314475
Name: two, dtype: float64

In [23]:
df.sub(row, axis="columns")

one       two     three
a -1.051306 -2.203147       NaN
b  0.000000  0.000000  0.000000
c -1.294851 -0.510571 -0.171045
d       NaN -1.818764 -1.609817

In [24]:
df.sub(row, axis=1)

one       two     three
a -1.051306 -2.203147       NaN
b  0.000000  0.000000  0.000000
c -1.294851 -0.510571 -0.171045
d       NaN -1.818764 -1.609817

In [25]:
df.sub(column, axis="index")

one  two     three
a  1.041167  0.0       NaN
b -0.110674  0.0 -1.589272
c -0.894953  0.0 -1.249745
d       NaN  0.0 -1.380325

In [26]:
df.sub(column, axis=0)

one  two     three
a  1.041167  0.0       NaN
b -0.110674  0.0 -1.589272
c -0.894953  0.0 -1.249745
d       NaN  0.0 -1.380325

In [27]:
#Furthermore you can align a level of a MultiIndexed DataFrame with a Series.
dfmi = df.copy()

dfmi.index = pd.MultiIndex.from_tuples(

    [(1, "a"), (1, "b"), (1, "c"), (2, "a")], names=["first", "second"]

)

In [28]:
dfmi

one       two     three
first second                              
1     a       0.342308 -0.698858       NaN
      b       1.393615  1.504289 -0.084983
      c       0.098764  0.993717 -0.256028
2     a            NaN -0.314475 -1.694800

In [29]:
dfmi.sub(column, axis=0, level="second")

one       two     three
first second                              
1     a       1.041167  0.000000       NaN
      b      -0.110674  0.000000 -1.589272
      c      -0.894953  0.000000 -1.249745
2     a            NaN  0.384384 -0.995942

In [30]:
s = pd.Series(np.arange(10))
s

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [31]:
div, rem = divmod(s, 3)
div

0    0
1    0
2    0
3    1
4    1
5    1
6    2
7    2
8    2
9    3
dtype: int32

In [32]:
rem

0    0
1    1
2    2
3    0
4    1
5    2
6    0
7    1
8    2
9    0
dtype: int32

In [33]:
idx = pd.Index(np.arange(10))
idx

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int32')

In [34]:
div, rem = divmod(idx, 3)
div

Index([0, 0, 0, 1, 1, 1, 2, 2, 2, 3], dtype='int32')

In [35]:
rem

Index([0, 1, 2, 0, 1, 2, 0, 1, 2, 0], dtype='int32')

In [36]:
div, rem = divmod(s, [2, 2, 3, 3, 4, 4, 5, 5, 6, 6])
div

0    0
1    0
2    0
3    1
4    1
5    1
6    1
7    1
8    1
9    1
dtype: int32

In [37]:
rem

0    0
1    1
2    2
3    0
4    0
5    1
6    1
7    2
8    2
9    3
dtype: int32

In [38]:
#missing data operations
df2 = df.copy()
df2

one       two     three
a  0.342308 -0.698858       NaN
b  1.393615  1.504289 -0.084983
c  0.098764  0.993717 -0.256028
d       NaN -0.314475 -1.694800

In [39]:
df2.loc["a", "three"] = 1.0
df2

one       two     three
a  0.342308 -0.698858  1.000000
b  1.393615  1.504289 -0.084983
c  0.098764  0.993717 -0.256028
d       NaN -0.314475 -1.694800

In [40]:
df + df2

one       two     three
a  0.684617 -1.397717       NaN
b  2.787230  3.008578 -0.169966
c  0.197528  1.987435 -0.512056
d       NaN -0.628950 -3.389600

In [41]:
df.add(df2, fill_value=0)

one       two     three
a  0.684617 -1.397717  1.000000
b  2.787230  3.008578 -0.169966
c  0.197528  1.987435 -0.512056
d       NaN -0.628950 -3.389600

In [42]:
df2.add(df, fill_value=0)

one       two     three
a  0.684617 -1.397717  1.000000
b  2.787230  3.008578 -0.169966
c  0.197528  1.987435 -0.512056
d       NaN -0.628950 -3.389600

In [43]:
df.gt(df2)

one    two  three
a  False  False  False
b  False  False  False
c  False  False  False
d  False  False  False

In [44]:
df2.ne(df)

one    two  three
a  False  False   True
b  False  False  False
c  False  False  False
d   True  False  False

In [48]:
df

one       two     three
a  0.342308 -0.698858       NaN
b  1.393615  1.504289 -0.084983
c  0.098764  0.993717 -0.256028
d       NaN -0.314475 -1.694800

In [45]:
df > 0

one    two  three
a   True  False  False
b   True   True  False
c   True   True  False
d  False  False  False

In [46]:
(df > 0).all()

one      False
two      False
three    False
dtype: bool

In [47]:
(df > 0).any()

one       True
two       True
three    False
dtype: bool

In [49]:
(df > 0).any().any()

True

In [50]:
df.empty

False

In [51]:
pd.DataFrame(columns=list("ABC")).empty

True

In [52]:
df + df == df * 2

one   two  three
a   True  True  False
b   True  True   True
c   True  True   True
d  False  True   True

In [53]:
(df + df == df * 2).all()

one      False
two       True
three    False
dtype: bool

In [54]:
np.nan == np.nan

False

In [55]:
(df + df).equals(df * 2)

True

In [56]:
df1 = pd.DataFrame({"col": ["foo", 0, np.nan]})

df2 = pd.DataFrame({"col": [np.nan, 0, "foo"]}, index=[2, 1, 0])

In [57]:
df1

col
0  foo
1    0
2  NaN

In [58]:
df2

col
2  NaN
1    0
0  foo

In [59]:
df1.equals(df2)

False

In [61]:
df2.sort_index()

col
0  foo
1    0
2  NaN

In [60]:
df1.equals(df2.sort_index())

True

In [62]:
pd.Series(["foo", "bar", "baz"]) == "foo"

0     True
1    False
2    False
dtype: bool

In [64]:
type(pd.Series(["foo", "bar", "baz"]) == "foo")

pandas.core.series.Series

In [63]:
pd.Index(["foo", "bar", "baz"]) == "foo"

array([ True, False, False])

In [65]:
type(pd.Index(["foo", "bar", "baz"]) == "foo")

numpy.ndarray

In [66]:
pd.Series(["foo", "bar", "baz"]) == pd.Index(["foo", "bar", "qux"])

0     True
1     True
2    False
dtype: bool

In [67]:
pd.Series(["foo", "bar", "baz"]) == np.array(["foo", "bar", "qux"])

0     True
1     True
2    False
dtype: bool

In [68]:
df1 = pd.DataFrame(

    {"A": [1.0, np.nan, 3.0, 5.0, np.nan], "B": [np.nan, 2.0, 3.0, np.nan, 6.0]}

)



df2 = pd.DataFrame(

    {

        "A": [5.0, 2.0, 4.0, np.nan, 3.0, 7.0],

        "B": [np.nan, np.nan, 3.0, 4.0, 6.0, 8.0],

    }

)

In [69]:
df1

A    B
0  1.0  NaN
1  NaN  2.0
2  3.0  3.0
3  5.0  NaN
4  NaN  6.0

In [70]:
df2

A    B
0  5.0  NaN
1  2.0  NaN
2  4.0  3.0
3  NaN  4.0
4  3.0  6.0
5  7.0  8.0

In [71]:
df1.combine_first(df2)

A    B
0  1.0  NaN
1  2.0  2.0
2  3.0  3.0
3  5.0  4.0
4  3.0  6.0
5  7.0  8.0

In [72]:
def combiner(x, y):
    return np.where(pd.isna(x), y, x)

In [73]:
df1.combine(df2, combiner)

A    B
0  1.0  NaN
1  2.0  2.0
2  3.0  3.0
3  5.0  4.0
4  3.0  6.0
5  7.0  8.0

In [74]:
df

one       two     three
a  0.342308 -0.698858       NaN
b  1.393615  1.504289 -0.084983
c  0.098764  0.993717 -0.256028
d       NaN -0.314475 -1.694800

In [75]:
df.mean(0)

one      0.611562
two      0.371168
three   -0.678604
dtype: float64

In [76]:
df.mean(1)

a   -0.178275
b    0.937640
c    0.278818
d   -1.004638
dtype: float64

In [77]:
df.sum(0, skipna=False)

one           NaN
two      1.484673
three         NaN
dtype: float64

In [78]:
df.sum(axis=1, skipna=True)

a   -0.356550
b    2.812921
c    0.836454
d   -2.009275
dtype: float64

In [81]:
df.mean()

one      0.611562
two      0.371168
three   -0.678604
dtype: float64

In [83]:
df.mean(1)

a   -0.178275
b    0.937640
c    0.278818
d   -1.004638
dtype: float64

In [82]:
df.std()

one      0.688137
two      1.046676
three    0.884198
dtype: float64

In [79]:
ts_stand = (df - df.mean()) / df.std()

ts_stand.std()

one      1.0
two      1.0
three    1.0
dtype: float64

In [85]:
ts_stand

one       two     three
a -0.391279 -1.022309       NaN
b  1.136477  1.082589  0.671366
c -0.745198  0.594787  0.477920
d       NaN -0.655067 -1.149287

In [80]:
xs_stand = df.sub(df.mean(1), axis=0).div(df.std(1), axis=0)

xs_stand.std(1)

a    1.0
b    1.0
c    1.0
d    1.0
dtype: float64

In [87]:
df

one       two     three
a  0.342308 -0.698858       NaN
b  1.393615  1.504289 -0.084983
c  0.098764  0.993717 -0.256028
d       NaN -0.314475 -1.694800

In [86]:
df.cumsum()

one       two     three
a  0.342308 -0.698858       NaN
b  1.735923  0.805430 -0.084983
c  1.834687  1.799148 -0.341011
d       NaN  1.484673 -2.035811

In [88]:
np.mean(df["one"])

0.6115624781508879

In [89]:
df["one"].mean()

0.6115624781508879

In [91]:
np.mean(df["one"].to_numpy())

nan

In [92]:
series = pd.Series(np.random.randn(500))

series[20:500] = np.nan

series[10:20] = 5

series.nunique()

11

In [93]:
series = pd.Series(np.random.randn(1000))

series[::2] = np.nan

series.describe()

count    500.000000
mean       0.002191
std        1.023972
min       -2.545618
25%       -0.703997
50%       -0.021504
75%        0.663194
max        3.580700
dtype: float64

In [95]:
frame = pd.DataFrame(np.random.randn(1000, 5), columns=["a", "b", "c", "d", "e"])

frame.iloc[::2] = np.nan

frame

a         b         c         d         e
0         NaN       NaN       NaN       NaN       NaN
1   -0.640765  0.903101  0.938694  0.086676  0.214302
2         NaN       NaN       NaN       NaN       NaN
3   -0.543897 -2.615456  1.157518  1.095664 -0.494296
4         NaN       NaN       NaN       NaN       NaN
..        ...       ...       ...       ...       ...
995 -1.373696 -0.768637  0.824005 -1.154017 -1.310304
996       NaN       NaN       NaN       NaN       NaN
997  0.358162  0.550522 -0.452393  0.680302 -0.313340
998       NaN       NaN       NaN       NaN       NaN
999  0.312122  0.407514 -0.638628  0.388613 -1.140821

[1000 rows x 5 columns]

In [96]:
frame.describe()

a           b           c           d           e
count  500.000000  500.000000  500.000000  500.000000  500.000000
mean     0.010974    0.021146   -0.011155    0.069428   -0.033026
std      1.004994    0.988079    0.996350    1.005681    0.951650
min     -2.858664   -2.615456   -2.861155   -3.002902   -3.255303
25%     -0.692149   -0.632836   -0.701961   -0.580114   -0.650566
50%      0.019151    0.019034   -0.053929    0.045881   -0.076880
75%      0.719754    0.697630    0.651049    0.723683    0.618942
max      2.742931    2.545021    3.652229    3.294840    3.373784

In [97]:
series.describe(percentiles=[0.05, 0.25, 0.75, 0.95])

count    500.000000
mean       0.002191
std        1.023972
min       -2.545618
5%        -1.703468
25%       -0.703997
50%       -0.021504
75%        0.663194
95%        1.755931
max        3.580700
dtype: float64

In [100]:
s = pd.Series(["a", "a", "b", "b", "a", "a", np.nan, "c", "d", "a"])
s

0      a
1      a
2      b
3      b
4      a
5      a
6    NaN
7      c
8      d
9      a
dtype: object

In [101]:
s.describe()

count     9
unique    4
top       a
freq      5
dtype: object

In [102]:
frame = pd.DataFrame({"a": ["Yes", "Yes", "No", "No"], "b": range(4)})
frame

a  b
0  Yes  0
1  Yes  1
2   No  2
3   No  3

In [103]:
frame.describe()

b
count  4.000000
mean   1.500000
std    1.290994
min    0.000000
25%    0.750000
50%    1.500000
75%    2.250000
max    3.000000

In [104]:
frame.describe(include=["object"])

a
count     4
unique    2
top     Yes
freq      2

In [105]:
frame.describe(include=["number"])

b
count  4.000000
mean   1.500000
std    1.290994
min    0.000000
25%    0.750000
50%    1.500000
75%    2.250000
max    3.000000

In [106]:
frame.describe(include="all")

a         b
count     4  4.000000
unique    2       NaN
top     Yes       NaN
freq      2       NaN
mean    NaN  1.500000
std     NaN  1.290994
min     NaN  0.000000
25%     NaN  0.750000
50%     NaN  1.500000
75%     NaN  2.250000
max     NaN  3.000000

In [108]:
s1 = pd.Series(np.random.randn(5))
s1

0    0.416804
1    0.599824
2    1.061644
3    0.475948
4    0.219582
dtype: float64

In [109]:
s1.idxmin(), s1.idxmax()

(4, 2)

In [110]:
df1 = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])

df1

A         B         C
0 -0.963447 -0.353149 -0.749629
1 -1.223804  1.442604 -0.526273
2 -0.138254  0.559683  0.190601
3 -2.039707 -0.957862  0.248311
4  0.400016 -0.040743  0.654431

In [111]:
df1.idxmin(axis=0)

A    3
B    3
C    0
dtype: int64

In [113]:
df1.idxmax(axis=1)

0    B
1    B
2    B
3    C
4    C
dtype: object

In [114]:
df3 = pd.DataFrame([2, 1, 1, 3, np.nan], columns=["A"], index=list("edcba"))

df3

A
e  2.0
d  1.0
c  1.0
b  3.0
a  NaN

In [115]:
df3["A"].idxmin()

'd'

In [116]:
data = np.random.randint(0, 7, size=50)

data

array([6, 5, 1, 1, 3, 6, 4, 4, 2, 5, 2, 5, 1, 4, 3, 0, 5, 0, 1, 3, 1, 1,
       1, 2, 6, 5, 5, 3, 5, 3, 1, 1, 2, 1, 2, 2, 5, 3, 5, 4, 1, 1, 4, 5,
       5, 0, 5, 3, 0, 4])

In [117]:
s = pd.Series(data)

s.value_counts()

5    12
1    12
3     7
4     6
2     6
0     4
6     3
Name: count, dtype: int64

In [118]:
data = {"a": [1, 2, 3, 4], "b": ["x", "x", "y", "y"]}

frame = pd.DataFrame(data)

frame

a  b
0  1  x
1  2  x
2  3  y
3  4  y

In [119]:
frame.value_counts()

a  b
1  x    1
2  x    1
3  y    1
4  y    1
Name: count, dtype: int64

In [120]:
s5 = pd.Series([1, 1, 3, 3, 3, 5, 5, 7, 7, 7])

s5.mode()

0    3
1    7
dtype: int64

In [126]:
df5 = pd.DataFrame(

    {

        "A": np.random.randint(0, 7, size=50),

        "B": np.random.randint(-10, 15, size=50),

    }

)

df5.head()

A   B
0  3   9
1  4  -8
2  6   8
3  2   5
4  2  11

In [127]:
df5.mode()

A  B
0  4  4

In [128]:
arr = np.random.randn(20)

arr

array([ 1.08398043, -0.12091578, -0.34865767, -0.7361803 , -0.75451588,
       -0.51104198,  2.13189682,  0.48958342,  1.02261704, -2.2568324 ,
        0.75001553, -0.82640328,  0.22246626, -0.71057076, -0.73159076,
        1.06369519,  1.91975033,  1.3028142 , -1.34650138, -0.99014711])

In [142]:
factor = pd.cut(arr, 4)
factor

[(1.035, 2.132], (-1.16, -0.0625], (-1.16, -0.0625], (-1.16, -0.0625], (-1.16, -0.0625], ..., (1.035, 2.132], (1.035, 2.132], (1.035, 2.132], (-2.261, -1.16], (-1.16, -0.0625]]
Length: 20
Categories (4, interval[float64, right]): [(-2.261, -1.16] < (-1.16, -0.0625] < (-0.0625, 1.035] < (1.035, 2.132]]

In [143]:
factor[0]

Interval(1.035, 2.132, closed='right')

In [131]:
factor = pd.cut(arr, [-5, -1, 0, 1, 5])

factor

[(1, 5], (-1, 0], (-1, 0], (-1, 0], (-1, 0], ..., (1, 5], (1, 5], (1, 5], (-5, -1], (-1, 0]]
Length: 20
Categories (4, interval[int64, right]): [(-5, -1] < (-1, 0] < (0, 1] < (1, 5]]

In [144]:
arr = np.random.randn(30)

factor = pd.qcut(arr, [0, 0.25, 0.5, 0.75, 1])

factor

[(0.633, 2.087], (0.0851, 0.633], (0.633, 2.087], (0.633, 2.087], (-0.738, 0.0851], ..., (-2.538, -0.738], (-2.538, -0.738], (0.0851, 0.633], (0.633, 2.087], (-0.738, 0.0851]]
Length: 30
Categories (4, interval[float64, right]): [(-2.538, -0.738] < (-0.738, 0.0851] < (0.0851, 0.633] < (0.633, 2.087]]

In [145]:
arr = np.random.randn(20)

factor = pd.cut(arr, [-np.inf, 0, np.inf])

factor

[(0.0, inf], (0.0, inf], (-inf, 0.0], (-inf, 0.0], (-inf, 0.0], ..., (-inf, 0.0], (-inf, 0.0], (-inf, 0.0], (0.0, inf], (-inf, 0.0]]
Length: 20
Categories (2, interval[float64, right]): [(-inf, 0.0] < (0.0, inf]]

In [146]:
def extract_city_name(df):

    """

    Chicago, IL -> Chicago for city_name column

    """

    df["city_name"] = df["city_and_code"].str.split(",").str.get(0)

    return df



def add_country_name(df, country_name=None):

    """

    Chicago -> Chicago-US for city_name column

    """

    col = "city_name"

    df["city_and_country"] = df[col] + country_name

    return df



df_p = pd.DataFrame({"city_and_code": ["Chicago, IL"]})
df_p

city_and_code
0   Chicago, IL

In [147]:
add_country_name(extract_city_name(df_p), country_name="US")

city_and_code city_name city_and_country
0   Chicago, IL   Chicago        ChicagoUS

In [148]:
df_p.pipe(extract_city_name).pipe(add_country_name, country_name="US")

city_and_code city_name city_and_country
0   Chicago, IL   Chicago        ChicagoUS

In [155]:
import statsmodels.formula.api as sm

bb = pd.read_csv(r"C:\Users\YOSSI\Downloads/baseball.csv", index_col="id")

In [156]:
(

    bb.query("h > 0")

    .assign(ln_h=lambda df: np.log(df.h))

    .pipe((sm.ols, "data"), "hr ~ ln_h + year + g + C(lg)")

    .fit()

    .summary()

)

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                     hr   R-squared:                       0.685
Model:                            OLS   Adj. R-squared:                  0.665
Method:                 Least Squares   F-statistic:                     34.28
Date:                Thu, 17 Oct 2024   Prob (F-statistic):           3.48e-15
Time:                        19:50:47   Log-Likelihood:                -205.92
No. Observations:                  68   AIC:                             421.8
Df Residuals:                      63   BIC:                             432.9
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept   -8484.7720   4664.146     -1.819      0.074   -1.78e+04     835.780
C(lg)[T.NL]    -2.2736      1.325     -1.716      0.091      -4.922       0.375
ln_h           -1.3542      0.875     -1.547      0.127      -3.103       0.395
year            4.2277      2.324      1.819      0.074      -0.417       8.872
g               0.1841      0.029      6.258      0.000       0.125       0.243
==============================================================================
Omnibus:                       10.875   Durbin-Watson:                   1.999
Prob(Omnibus):                  0.004   Jarque-Bera (JB):               17.298
Skew:                           0.537   Prob(JB):                     0.000175
Kurtosis:                       5.225   Cond. No.                     1.49e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.49e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [158]:
df

one       two     three
a  0.342308 -0.698858       NaN
b  1.393615  1.504289 -0.084983
c  0.098764  0.993717 -0.256028
d       NaN -0.314475 -1.694800

In [157]:
df.apply(lambda x: np.mean(x))

one      0.611562
two      0.371168
three   -0.678604
dtype: float64

In [159]:
df.apply(lambda x: np.mean(x), axis=1)

a   -0.178275
b    0.937640
c    0.278818
d   -1.004638
dtype: float64

In [160]:
df.apply(lambda x: x.max() - x.min())

one      1.294851
two      2.203147
three    1.609817
dtype: float64

In [161]:
df.apply(np.cumsum)

one       two     three
a  0.342308 -0.698858       NaN
b  1.735923  0.805430 -0.084983
c  1.834687  1.799148 -0.341011
d       NaN  1.484673 -2.035811

In [162]:
df.apply(np.exp)

one       two     three
a  1.408195  0.497152       NaN
b  4.029389  4.500952  0.918528
c  1.103806  2.701258  0.774120
d       NaN  0.730172  0.183636

In [163]:
df.apply("mean")

one      0.611562
two      0.371168
three   -0.678604
dtype: float64

In [164]:
df.apply("mean", axis=1)

a   -0.178275
b    0.937640
c    0.278818
d   -1.004638
dtype: float64

In [165]:
tsdf = pd.DataFrame(

    np.random.randn(1000, 3),

    columns=["A", "B", "C"],

    index=pd.date_range("1/1/2000", periods=1000),

)



tsdf.apply(lambda x: x.idxmax())

A   2001-05-14
B   2002-07-30
C   2000-09-30
dtype: datetime64[ns]

In [166]:
def subtract_and_divide(x, sub, divide=1):

    return (x - sub) / divide



df_udf = pd.DataFrame(np.ones((2, 2)))

df_udf.apply(subtract_and_divide, args=(5,), divide=3)

0         1
0 -1.333333 -1.333333
1 -1.333333 -1.333333

In [167]:
tsdf = pd.DataFrame(

    np.random.randn(10, 3),

    columns=["A", "B", "C"],

    index=pd.date_range("1/1/2000", periods=10),

)



tsdf.iloc[3:7] = np.nan

In [168]:
tsdf

A         B         C
2000-01-01 -0.666660  0.224600 -2.100259
2000-01-02  1.376065 -1.065364 -1.939103
2000-01-03  0.069356 -0.260523  0.073013
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08 -1.190028 -0.936135  0.653488
2000-01-09  0.004559  0.521101  1.135044
2000-01-10 -0.366584  0.192615 -0.625746

In [169]:
tsdf.apply(pd.Series.interpolate)

A         B         C
2000-01-01 -0.666660  0.224600 -2.100259
2000-01-02  1.376065 -1.065364 -1.939103
2000-01-03  0.069356 -0.260523  0.073013
2000-01-04 -0.182521 -0.395646  0.189108
2000-01-05 -0.434398 -0.530768  0.305203
2000-01-06 -0.686275 -0.665890  0.421298
2000-01-07 -0.938152 -0.801012  0.537393
2000-01-08 -1.190028 -0.936135  0.653488
2000-01-09  0.004559  0.521101  1.135044
2000-01-10 -0.366584  0.192615 -0.625746

In [170]:
tsdf.agg(lambda x: np.sum(x))

A   -0.773293
B   -1.323706
C   -2.803564
dtype: float64

In [171]:
tsdf.agg("sum")

A   -0.773293
B   -1.323706
C   -2.803564
dtype: float64

In [172]:
# these are equivalent to a ``.sum()`` because we are aggregating
# on a single function

tsdf.sum()

A   -0.773293
B   -1.323706
C   -2.803564
dtype: float64

In [173]:
tsdf["A"].agg("sum")

-0.773292931368611

In [174]:
tsdf.agg(["sum", "mean"])

A         B         C
sum  -0.773293 -1.323706 -2.803564
mean -0.128882 -0.220618 -0.467261

In [175]:
tsdf["A"].agg(["sum", "mean"])

sum    -0.773293
mean   -0.128882
Name: A, dtype: float64

In [176]:
tsdf["A"].agg(["sum", lambda x: x.mean()])

sum        -0.773293
<lambda>   -0.128882
Name: A, dtype: float64

In [177]:
def mymean(x):

    return x.mean()



tsdf["A"].agg(["sum", mymean])

sum      -0.773293
mymean   -0.128882
Name: A, dtype: float64

In [178]:
tsdf

A         B         C
2000-01-01 -0.666660  0.224600 -2.100259
2000-01-02  1.376065 -1.065364 -1.939103
2000-01-03  0.069356 -0.260523  0.073013
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08 -1.190028 -0.936135  0.653488
2000-01-09  0.004559  0.521101  1.135044
2000-01-10 -0.366584  0.192615 -0.625746

In [179]:
tsdf.agg({"A": "mean", "B": "sum"})

A   -0.128882
B   -1.323706
dtype: float64

In [180]:
tsdf.agg({"A": ["mean", "min"], "B": "sum"})

A         B
mean -0.128882       NaN
min  -1.190028       NaN
sum        NaN -1.323706

In [181]:
from functools import partial

q_25 = partial(pd.Series.quantile, q=0.25)

q_25.__name__ = "25%"

q_75 = partial(pd.Series.quantile, q=0.75)

q_75.__name__ = "75%"

tsdf.agg(["count", "mean", "std", "min", q_25, "median", q_75, "max"])

A         B         C
count   6.000000  6.000000  6.000000
mean   -0.128882 -0.220618 -0.467261
std     0.871058  0.655176  1.339662
min    -1.190028 -1.065364 -2.100259
25%    -0.591641 -0.767232 -1.610764
median -0.181013 -0.033954 -0.276367
75%     0.053157  0.216604  0.508369
max     1.376065  0.521101  1.135044

In [182]:
tsdf = pd.DataFrame(

    np.random.randn(10, 3),

    columns=["A", "B", "C"],

    index=pd.date_range("1/1/2000", periods=10),

)



tsdf.iloc[3:7] = np.nan

tsdf

A         B         C
2000-01-01 -1.095191  0.237926 -0.752956
2000-01-02  0.196347 -0.239966 -0.431888
2000-01-03 -0.152079  0.748230 -0.180869
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08 -1.473149  0.174117 -0.969409
2000-01-09  0.617741 -1.414483 -0.047319
2000-01-10 -1.282051 -0.086657  0.746800